config/routes.rb
Rails.application.routes.draw do
  root "stories#index"
  resources :stories
  resources :comments
  resources :response_comments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :story
  has_many :response_comments, dependent: :destroy

  validates :user, presence: true
  validates :content, presence: true
end

app/models/response_comment.rb
class ResponseComment < ApplicationRecord
  belongs_to :comment

  validates :content, presence: true
  validates :user, presence: true
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
    @story = Story.find(params[:story_id])
  end

  def show
    @comment = Comment.find(params[:id])
    @story = @comment.story
  end

  def create

    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment was successfully created."
      redirect_to stories_path
    else
      flash[:notice] = "Comment was not created details needed"
      redirect_to new_comment_path
    end
  end

  def edit

  end

  def update
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user, :story_id)
  end
end

app/controllers/response_comments_controller.rb
class ResponseCommentsController < ApplicationController
  def index
    @response_comments = ResponseComment.all
  end

  def new
    @response_comment = ResponseComment.new
    @comment = Comment.find(params[:comment_id])
  end

  def show
    @response_comment = ResponseComment.find(params[:id])
    @response_comment = @response_comment.comment
  end

  def create

    response = ResponseComment.find(params[:response_id])
    @response_comment = ResponseComment.new(response_comment_params)
    if @response_comment.save
      flash[:notice] = "Successfully created response comment."
      redirect_to stories_path
    else
      flash[:notice] = "Unable to create response comment details needed."
      redirect_to new_response_comment_path
    end

  end

  def edit
  end

  def update
  end

  private

  def response_comment_params
    params.require(:response_comment).permit(:content, :user, :comment_id, :response_id)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index

    @stories =  Story.all.order("created_at DESC")
  end

  def new
    @story = Story.new
  end

  def show
    @story = Story.find(params[:id])
    story = Story.find(params[:id])
    @comments = Comment.where(story_id: story.id).order("created_at DESC")
   
  end

  def create
    @story = Story.new(story_params)
    if @story.save
    flash[:notice] = "Story was successfully created."
    redirect_to story_path(@story)
    else
      flash[:notice] = "Story was not created details needed."
      redirect_to new_story_path
    end
  end

  def edit
    @story= Story.find(params[:id])
  end

  def update
    @story= Story.find(params[:id])
    like=(@story.upvotes.to_i || 0)+1
    @story.update(upvotes: like)

    flash[:notice] = "Story was successfully updated."
    redirect_to story_path(@story)
  end


  private

  def story_params
    params.require(:story).permit(:title, :url,:description, :upvotes, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/response_comments_helper.rb
module ResponseCommentsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<%= link_to "Home", stories_path %>
<h1>Comments</h1>
<% @comments.each do |comment| %>
  <h2>Id: <%= comment.id %> <%= comment.user %></h2>
  <h5><%= comment.content %></h5>
  <%= link_to "Add Responsive Comment", new_response_comment_path(comment_id: comment.id) %>
<% end %>

app/views/comments/new.html.erb
<h1>Create Comments</h1>
<div class="button"><%= link_to "Home", stories_path %></div>
<div class="container">
<%= form_with model: @comment, path: comments_path, method: :post do |f| %>
    <h2>Comments</h2>
  <%= f.hidden_field :story_id, value: @story.id %>
  <div class="form">
    <label>Content: </label>
    <%= f.text_area :content %>
  </div>
  <div class="form">
    <label>User: </label>
    <%= f.text_field :user %>
  </div>

  <%= f.submit "Add Comment", class: "button" %>
<% end %>
</div>

app/views/comments/show.html.erb
<%= link_to "Comments Page", comments_path %>
<h1>Comments</h1>
<h3><%= @comment.content %></h3>
<h5><%= @comment.user %></h5>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Story Page" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<%= yield %>
</body>
</html>

app/views/response_comments/create.html.erb
<h1>ResponseComments#create</h1>
<p>Find me in app/views/response_comments/create.html.erb</p>

app/views/response_comments/edit.html.erb
<h1>ResponseComments#edit</h1>
<p>Find me in app/views/response_comments/edit.html.erb</p>

app/views/response_comments/index.html.erb
<h1>ResponseComments</h1>

<% @response_comments.each do |response| %>
  <h3><%= response.user %></h3>
  <h5><%= response.content %></h5>
<% end %>

app/views/response_comments/new.html.erb
<h1> Create Response Comments</h1>
<div class="button"><%= link_to "Home", stories_path %></div>
<div class="container">
  <%= form_with model: @response_comment, path: response_comments_path, method: :post do |f| %>
    <h2>Response Comments</h2>
    <%= f.hidden_field :comment_id, value: @comment.id %>
    <div class="form">
      <label>Content</label>
      <%= f.text_area :content %>
    </div>
    <div class="form">
      <label>User</label>
      <%= f.text_field :user %>
    </div>
    <%= f.submit "Add Response Comment", class: "button" %>
  <% end %>
</div>

app/views/response_comments/show.html.erb
<%= link_to "Home", stories_path %>
<h1>ResponseComments</h1>
<h2><%= @response_comment.content %></h2>
<h4><%= @response_comment.user %></h4>

app/views/response_comments/update.html.erb
<h1>ResponseComments#update</h1>
<p>Find me in app/views/response_comments/update.html.erb</p>

app/views/stories/create.html.erb
<h1>Story#create</h1>
<p>Find me in app/views/story/create.html.erb</p>

app/views/stories/edit.html.erb
<h1>Story#edit</h1>
<p>Find me in app/views/story/edit.html.erb</p>

app/views/stories/index.html.erb
<div class="button"><%= link_to "Create Story", new_story_path %></div>

<h1>List of Posts</h1>
<div class="post">
  <% @stories.each do |story| %>
    <h3><a href="<%= story.url %>" target=" _blank"><%= story['title'] %></a></h3>

    <h4><%= story.description %></h4>
    <div class="commentcount">
      <div class="commentcount">
        <span><%= button_to "👍", story_path(story), method: :patch %></span>
        <span class="spanelement"><%= story.upvotes %> Likes</span>
     </div>
      <% story_id = story.id %>
      <% count = Comment.where(story_id: story_id).count  %>
      <% comments = Comment.where(story_id: story_id).pluck(:id) %>
      <% comments.each do |id| %>
        <% resposnsecoment= ResponseComment.where(comment_id: id).count %>
        <% count= count+resposnsecoment %>
      <% end %>
      <%# comment_id= comments&.id%>
      <%# resposnsecoment= ResponseComment.where(comment_id: comment_id).count %>

      <div class="comment"> <p><%= count  %> Comments</p></div>
    </div>

    <div class="button"><%= link_to "Show Comments", story_path(story) %></div>
  <% end %>
</div>

app/views/stories/new.html.erb
<h1>Create Story</h1>
<div class="button"><%= link_to "Home", stories_path %></div>

<div class="container">
  <%= form_with model: @story, path: stories_path, method: :post do |f| %>
    <div class="form">
      <label>Title: </label>
      <%= f.text_field :title %>
    </div>
    <div class="form">
      <label>URL: </label>
      <%= f.text_field :url %>
    </div>
    <div class="form">
      <label>Description: </label>
      <%= f.text_area :description %>
    </div>
    <div class="form">
      <label>User Name: </label>
      <%= f.text_field :user %>
    </div>
    <div class="form">
      <lable>Likes:</lable>
      <%= f.select :upvotes, options_for_select([[0, 0], [1, 1]]) %>
    </div>
    <%= f.submit "Create Story", class: "button" %>
  <% end %>
</div>

app/views/stories/show.html.erb
<div class="button"><%= link_to "Home", stories_path %></div>
<div class="post">
<h2>Comment Section</h2>
<h2><%= @story.user %></h2>
<h3><%= @story.title %></h3>
<h5><%= @story.description %></h5>
<p>👍 <%= @story.upvotes %> likes</p>
<div class="button"><%= link_to "✐ Add Comments", new_comment_path(story_id: @story.id) %></div>


<div class="comment">
  <% @comments.each do |comment| %>
    <h2>●<%= comment.user %></h2>
    <h4><%= comment.content %></h4>
    <h5><%= comment.created_at %></h5>
    <div class="button"><%= link_to "✐ Add Comment", new_response_comment_path(comment_id: comment.id) %></div>

    <div class="response">
      <% response_comment = ResponseComment.where(comment_id: comment.id).order("created_at DESC") %>
      <% response_comment.each do |response| %>
        <div>
          <h2>・<%= response.user %></h2>
          <h5><%= response.content %></h5>
          <p><%= response.created_at %></p>
          <div class="button"><%= link_to "✐ Add Comment", new_response_comment_path(comment_id: comment.id, response_id: response.id) %></div>

        </div>
      <% end %>
    </div>
  <% end %>
</div>
</div>

app/views/stories/update.html.erb
<h1>Story#update</h1>
<p>Find me in app/views/story/update.html.erb</p>